name: TestCI

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    #needs: testAllModes
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-


      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      # Show the structure of folder
      - name: Display structure of downloaded files
        run: ls -R
        #working-directory: build/iOS

  deletartifacts:
    name: Delete artifacts
    runs-on: ubuntu-latest
    #needs: testAllModes

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      # Show the structure of folder
      - name: Display structure of downloaded files
        run: ls -R
        #working-directory: build/iOS
